root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/yumeko ./cmd/yumeko"
bin = "./tmp/yumeko"
full_bin = "./tmp/yumeko"
include_ext = ["go", "toml"]
exclude_dir = ["tmp", "vendor", ".git", "data"]
include_dir = ["cmd", "internal"]
exclude_regex = ["_test.go"]
delay = 800
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"
rerun = false
rerun_delay = 500

[log]
time = true
main_only = false
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
